# Generated by Django 5.1 on 2024-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_categoryimage_category_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='sales/')),
                ('alt', models.CharField(default='Sales images', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesproduct',
            name='images',
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='images',
            field=models.ManyToManyField(to='product.saleimage'),
        ),
    ]
