# Generated by Django 5.1 on 2024-09-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_saleimage_remove_salesproduct_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesproduct',
            name='images',
        ),
        migrations.RemoveField(
            model_name='salesproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesproduct',
            name='title',
        ),
    ]
