# Generated by Django 5.1 on 2024-09-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_salesproduct_images_remove_salesproduct_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='specifications',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.specifications'),
        ),
    ]
